### ISSUE TITLE
Add js-beautify

### ISSUE THREAD

**Issue by jamlen** [Hewlett-Packard-ESS/docker-devenv-nodejs#1]
For the vim autoformat plugin to be able to format **Javascript** and **JSON** we need to have `js-beautify` installed.

```
npm install -g js-beautify
```

See [vim-autoformat/default-formatprograms](https://github.com/Chiel92/vim-autoformat#default-formatprograms)

**Comment by Stono** [comment]
https://github.com/Hewlett-Packard-ESS/docker-devenv-nodejs/commit/381e38f61dea0fc52a74044f2a455dc07d53fee2
